import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "../../providers/modal-provider";
import db from "@/lib/db";
import { ToasterProvider } from "../../providers/toast-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
      <html lang="en">
      <ModalProvider/>
        <body className={inter.className}>
        <ToasterProvider/>
        {children}</body>
      </html>
    </ClerkProvider>
  );
}
